name: 'Cancel on Screen Lock'
description: 'Cancel workflow when macOS screen is locked'
inputs:
  repo-token:
    description: 'github token that can cancel the run'
    required: true
runs:
  using: composite
  steps:
    - name: Check Runner
      id: check-runner
      run: ${{ github.action_path }}/check-self-hosted-runner.swift
      shell: bash
    - name: Cancel the workflow
      run: ${{ github.action_path }}/cancel-this-run.sh
      shell: bash
      env:
        SHOULD_CANCEL: ${{ steps.check-runner.outputs.screenLocked }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
branding:
  icon: monitor
  color: red
