name: 'Composite action'
description: 'Run swift command'
inputs:
  repo-token:
    description: 'github token'
    required: true
outputs:
  cancel:
    description: 'Should cancel workflow'
    value: ${{ steps.runner-check.outputs.cancel }}
runs:
  using: "composite"
  steps:
    - run: echo About to run swift in bash
      shell: bash
    - name: Check Runner
      id: runner-check
      run: ${{ github.action_path }}/check-self-hosted-runner.swift
      shell: bash
    - run: ${{ github.action_path }}/cancel-this-run.sh
      if: ${{ steps.runner-check.outputs.cancel == 'true' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
