name: 'Composite action'
description: 'Run swift command'
outputs:
  cancel:
    description: 'Should cancel workflow'
    value: ${{ steps.runner-check.outputs.cancel }}
runs:
  using: "composite"
  steps:
    - run: echo About to run swift in bash
      shell: bash
    - name: Check Runner
      id: runner-check
      run: ${{ github.action_path }}/check-self-hosted-runner.swift
      shell: bash
    - name: show environment
      run: env
      shell: bash
    - run: curl -X POST -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/cancel
      shell: bash
