name: 'Composite action'
description: 'Run swift command'
inputs:
  repo-token:
    description: 'github token that can cancel the run'
    required: true
runs:
  using: composite
  steps:
    - name: Check Runner
      run: ${{ github.action_path }}/check-self-hosted-runner.swift
      shell: bash
    - run: ${{ github.action_path }}/cancel-this-run.sh
      shell: bash
      env:
        SHOULD_CANCEL: ${{ steps.runner-check.outputs.screen-locked }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
