name: use-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  use-action:

    runs-on: macos-latest

    steps:
    - uses: sparta-science/composito@master
      with:
        repo-token: ${{ github.token }}
    - name: Check swift version
      run: swift --version
